---
# tasks file for roles/ec2
- name: Create an EC2 instance
  ec2:
    key_name: "{{ environment_name }}-key"
    region: "{{  ec2_region }}"
    group_id: "{{ sg_ec2.group_id }}"
    instance_type: "{{ instance_type }}"
    image: "{{ image }}"
    count_tag:
      env: "{{ environment_name }}"
    exact_count: 1
    wait: yes
    instance_tags:
      env: "{{ environment_name }}"
  register: ec2
- name: add the instance to group
  add_host: hostname={{ item.public_dns_name }} groups=web
  with_items: "{{ ec2.instances }}"
- name: wait for ssh server to be running
  wait_for: host={{ item.public_dns_name }} port=22 search_regex=OpenSSH
  with_items: "{{ ec2.instances }}"
