---
# tasks file for roles/ec2_keypair
- name: create a new EC2 key
  ec2_key:
    name: "{{ environment_name }}-key"
    region: "{{  ec2_region }}"
  register: ec2_key_result

- name: save private key
  copy:
    content: "{{ ec2_key_result.key.private_key }}"
    dest: "~/.aws/keys/privat-{{ environment_name }}-key.pem"
    mode: 0600
  when: ec2_key_result.changed
