- name: Deploy Docker container from Docker Hub to EC2 instans 
  hosts: localhost
  connection: local
  gather_facts: True

  vars_files:
    - group_vars/common.yml

  roles:
    - roles/securitygroups
    - roles/ec2_keypair
    - roles/ec2
- name: configure webservers
  hosts: web
  become: True
  remote_user: ubuntu
  gather_facts: True
  roles:
    - roles/nginxinc.nginx
  tasks:
    - name: delete default nginx index.html
      file:
        path: /usr/share/nginx/html/index.html
        state: absent
    - name: download and install new index.html from S3
      get_url:
        url: https://softservdemo.s3-eu-west-1.amazonaws.com/nginx/index.html
        dest: /usr/share/nginx/html/index.html
